# Generated by Django 3.2.9 on 2021-11-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/default-profile-pic.png', upload_to='profile_pics'),
        ),
    ]
