# Generated by Django 3.2.9 on 2021-11-05 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=100)),
                ('is_Specialized', models.BooleanField(default=False)),
                ('topic_created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='teachers',
        ),
        migrations.AddField(
            model_name='course',
            name='course_pic_URL',
            field=models.URLField(default='https://online.stanford.edu/sites/default/files/styles/figure_default/public/2018-03/education-creating-effective-online-blended-courses_gse-yo.p.e.n.jpg?itok=QUn6gWp5'),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('link', models.URLField()),
                ('class_created_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('class_pic_URL', models.URLField(default='https://media.istockphoto.com/vectors/communication-elearning-internet-network-as-knowledge-base-vector-id1059510610?k=20&m=1059510610&s=612x612&w=0&h=E3wbE9HsFSxUh6PcsCobIti-wfFrOD05jYHJl_a3yXQ=')),
                ('saturday', models.BooleanField(default=False)),
                ('satTime', models.TimeField(default='00:00')),
                ('sunday', models.BooleanField(default=False)),
                ('sunTime', models.TimeField(default='00:00')),
                ('monday', models.BooleanField(default=False)),
                ('monTime', models.TimeField(default='00:00')),
                ('tuesday', models.BooleanField(default=False)),
                ('tueTime', models.TimeField(default='00:00')),
                ('wednesday', models.BooleanField(default=False)),
                ('wedTime', models.TimeField(default='00:00')),
                ('thursday', models.BooleanField(default=False)),
                ('thuTime', models.TimeField(default='00:00')),
                ('friday', models.BooleanField(default=False)),
                ('friTime', models.TimeField(default='00:00')),
                ('class_participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.topics')),
            ],
        ),
    ]
