# Generated by Django 3.2.9 on 2021-11-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20211106_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='capacity',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
